// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY
import LoginButton from './LoginButton.vue'
import LogoutButton from './LogoutButton.vue'
// Export components individually
export { LoginButton, LogoutButton }
// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('LoginButton', LoginButton)
  Vue.component('LogoutButton', LogoutButton)
}
// Export the library as a plugin
export default { install: install }
